In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
type(a)

numpy.ndarray

In [4]:
b = np.array([[1,2,3],[4,5,6]], dtype=float)
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
d = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [7]:
a.ndim

1

In [8]:
b.ndim

2

In [9]:
c.ndim

2

In [10]:
d.ndim

3

In [11]:
a.shape

(3,)

In [12]:
b.shape

(2, 3)

In [13]:
c.shape

(3, 3)

In [14]:
d.shape

(1, 3, 3)

### Accessing/Changing specific elements, rows & columns etc.

In [15]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [16]:
a.shape

(2, 5)

In [17]:
a.ndim

2

In [18]:
a.dtype

dtype('int64')

In [20]:
a[0,3]

np.int64(4)

In [21]:
a[1,2]

np.int64(8)

In [23]:
a[0,4]

np.int64(5)

In [24]:
a[0,:]

array([1, 2, 3, 4, 5])

In [25]:
a[:,0]

array([1, 6])

In [26]:
a[0,0] = 7
a

array([[ 7,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
a[1,4] = 7
a

array([[7, 2, 3, 4, 5],
       [6, 7, 8, 9, 7]])

### Zeros/Ones method in NumPy

In [29]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.ones((3,3),dtype="int")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [33]:
np.full((3,3),7,dtype="int")

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [34]:
np.identity(3, dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [36]:
np.random.rand(3,3)

array([[0.7478232 , 0.45741149, 0.1731564 ],
       [0.75373687, 0.98304121, 0.37230413],
       [0.1387227 , 0.5028785 , 0.49759279]])

In [37]:
np.random.randint(1,7,size=(3,3),dtype="int")

array([[1, 1, 6],
       [5, 3, 4],
       [3, 4, 3]])

### Practice Questions
### Question #1
### Extract all the first 3 rows of the last 5 columns in a given numpy 2D array ‘a’?

In [38]:
a= np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])

In [39]:
a.shape

(5, 6)

In [40]:
a.ndim

2

In [41]:
a[:3, -5:]

array([[ 2,  3,  4,  5,  6],
       [20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12]])

### Question #2
### Given a positive number 'n' greater than 2, create a NumPy array of size (nxn) with all zeros and ones such that the ones make a shape of "+"

Examples:

Input 1:

3

Output 1:

[[0 1 0]

[1 1 1]

[0 1 0]]

Input 2:

5

Output 1:

[[0 0 1 0 0]

[0 0 1 0 0]

[1 1 1 1 1]

[0 0 1 0 0]

[0 0 1 0 0]]

In [43]:
n = 5
a = np.zeros((n,n),dtype='int')
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [45]:
a[n//2,:] = 1
a[:,n//2] = 1
a

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]])

### Arithmetic Operations with NumPy - Maths + Stats

In [54]:
a = np.array([[1,2,3,4], [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
a.max()

np.int64(8)

In [48]:
np.min(a)

np.int64(1)

In [49]:
a.sum()

np.int64(36)

In [50]:
np.mean(a)

np.float64(4.5)

In [51]:
a.max(axis=0)

array([5, 6, 7, 8])

In [52]:
a.max(axis=1)

array([4, 8])

In [53]:
a.sum(axis=1)

array([10, 26])